spring:
  application:
    name: demo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/employee_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    #  Change actual endpoint from we call api in frontend that's  /graphql
    graphiql:
    # Change UI test end point
    #  URL : localhost:8080/graphql2?path=graphql 
    # Bcz UI wants to know API endpoint everytime
      # path: /graphql2
      enabled: true

server:
  port: 8080